# Generated by Django 3.2.5 on 2022-03-03 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestAPI.registration'),
        ),
    ]
